name: reponame
dependencies:
- python
- plotly
- pandas
- numpy
- pip
- pip:
  - jupyter-book
  - "git+https://github.com/PSLmodels/microdf"
  - "git+https://github.com/ubicenter/ubicenter.py"
  - argparse
  - pyyaml
  - pathlib
  - typing